# Generated by Django 2.0.7 on 2018-09-05 00:22

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='品牌型号')),
            ],
            options={
                'verbose_name': '品牌型号',
                'verbose_name_plural': '品牌型号',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(choices=[('4G', '4G'), ('6G', '6G'), ('8G', '8G'), ('16G', '16G'), ('32G', '32G'), ('64G', '64G'), ('other', '其他')], max_length=10, verbose_name='内存大小')),
                ('screen_size', models.CharField(choices=[('1', '12.5寸'), ('2', '13寸'), ('3', '14寸'), ('4', '15.6寸'), ('5', '22寸'), ('6', '24寸'), ('7', '32寸'), ('other', '其他')], default='3', max_length=10, verbose_name='屏幕尺寸')),
                ('fiven_etwork', models.CharField(choices=[('no', '否'), ('yes', '是')], default='yes', max_length=10, verbose_name='5G网卡')),
                ('mac', models.CharField(max_length=50, verbose_name='mac地址')),
                ('os', models.CharField(choices=[('1', 'win7_x32'), ('2', 'win7_x64'), ('3', 'win10_x64'), ('4', 'windons_2008_x64'), ('5', 'windons_2012_r2_x64'), ('6', 'ubuntu'), ('7', 'centos'), ('8', 'macos'), ('9', '其他')], max_length=10, verbose_name='操作系统')),
                ('allot_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
                ('allot_times', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('state', models.CharField(choices=[('1', '使用中'), ('2', '空闲中'), ('3', '异常中')], default='1', max_length=10, verbose_name='状态')),
                ('tag', models.TextField(default='正常分配', verbose_name='备注')),
                ('brands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohan.Brand', verbose_name='电脑型号')),
            ],
            options={
                'verbose_name': '电脑信息',
                'verbose_name_plural': '电脑信息',
                'db_table': 'computer',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.CharField(max_length=50, verbose_name='CPU型号')),
            ],
            options={
                'verbose_name': 'CPU型号',
                'verbose_name_plural': 'CPU型号',
                'db_table': 'cpu',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=50, verbose_name='硬盘组合')),
            ],
            options={
                'verbose_name': '硬盘组合',
                'verbose_name_plural': '硬盘组合',
                'db_table': 'disk',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=10, verbose_name='职位')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('department', models.CharField(choices=[('1', '行政部'), ('2', '产品部'), ('3', '运营商业务部'), ('4', '充值业务部'), ('5', '财务部'), ('6', '智能饮水业务部'), ('7', '其它部门')], max_length=10, verbose_name='部门')),
                ('rank', models.CharField(choices=[('1', 'P1B'), ('2', 'P1A'), ('3', 'P2B'), ('4', 'P2A'), ('5', 'P3B'), ('6', 'P3A'), ('7', 'P4B'), ('8', 'P4A'), ('9', 'P5B'), ('10', 'P5A'), ('11', 'P6B'), ('12', 'P6A'), ('13', '未评级'), ('14', 'boss')], default='null', max_length=10, verbose_name='职级')),
                ('user_state', models.CharField(choices=[('1', '在职'), ('2', '离职')], default='1', max_length=10, verbose_name='在职状态')),
                ('com_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入职时间')),
                ('out_time', models.DateTimeField(auto_now=True, verbose_name='离职时间')),
                ('complete_state', models.BooleanField(default=False, verbose_name='分配状态')),
                ('tag', models.TextField(default='正常入职', verbose_name='备注')),
                ('positions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohan.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='computer',
            name='cpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohan.Cpu', verbose_name='cpu型号'),
        ),
        migrations.AddField(
            model_name='computer',
            name='disks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohan.Disk', verbose_name='硬盘组合'),
        ),
        migrations.AddField(
            model_name='computer',
            name='staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sohan.Staff', verbose_name='员工信息'),
        ),
    ]
