# Generated by Django 2.0.1 on 2018-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='memory',
            field=models.CharField(choices=[('4G', '4G'), ('6G', '6G'), ('8G', '8G'), ('10G', '10G'), ('12G', '12G'), ('16G', '16G'), ('32G', '32G'), ('64G', '64G'), ('other', '其他')], max_length=10, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(choices=[('1', 'win7_x32'), ('2', 'win7_x64'), ('3', 'win10_x64'), ('4', 'windons_2008_x64'), ('5', 'windons_2012_r2_x64'), ('6', 'ubuntu'), ('7', 'centos'), ('8', 'macos'), ('9', '其他')], default='3', max_length=10, verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='tag',
            field=models.TextField(default='使用1台', verbose_name='备注'),
        ),
    ]
